"""empty message

Revision ID: 274a3ff10837
Revises: 99da70c1ac0c
Create Date: 2016-08-06 20:28:37.163000

"""

# revision identifiers, used by Alembic.
revision = '274a3ff10837'
down_revision = '99da70c1ac0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    ### end Alembic commands ###
