"""empty message

Revision ID: 599f8bc1cd33
Revises: c76e3de3cd9a
Create Date: 2016-07-23 22:30:20.811000

"""

# revision identifiers, used by Alembic.
revision = '599f8bc1cd33'
down_revision = 'c76e3de3cd9a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    op.add_column(u'tags', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_index('tagname', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    op.drop_column(u'tags', 'tagname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tags', sa.Column('tagname', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('tagname', 'tags', ['tagname'], unique=True)
    op.drop_column(u'tags', 'name')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column(u'posts', 'category_id')
    op.drop_table('categories')
    ### end Alembic commands ###
