"""empty message

Revision ID: 65c3d7dff467
Revises: None
Create Date: 2016-07-25 21:18:06.832000

"""

# revision identifiers, used by Alembic.
revision = '65c3d7dff467'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('access_token_expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat')
    ### end Alembic commands ###
