"""empty message

Revision ID: 99da70c1ac0c
Revises: 65c3d7dff467
Create Date: 2016-07-26 16:42:13.550000

"""

# revision identifiers, used by Alembic.
revision = '99da70c1ac0c'
down_revision = '65c3d7dff467'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat')
    op.add_column('users', sa.Column('wechat_open_id', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wechat_open_id')
    op.create_table('wechat',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=56), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('access_token_expires_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
